### ISSUE TITLE
Referencing column 'endpoint_id' and referenced column 'id' in foreign key constraint 'endpoint_region_mapping_ibfk_1' are incompatible.

### ISSUE THREAD

**Issue by shurdanil** [cloudbase/coriolis#291]
Hello! Got this error into coriolis log

024-01-24 11:18:09.558 3351 CRITICAL coriolis [-] Unhandled error: oslo_db.exception.DBMigrationError: (pymysql.err.OperationalError) (3780, "Referencing column 'endpoint_id' and referenced column 'id' in foreign key constraint 'endpoint_region_mapping_ibfk_1' are incompatible.")
[SQL:
CREATE TABLE endpoint_region_mapping (
id VARCHAR(36) NOT NULL,
endpoint_id VARCHAR(36) NOT NULL,
region_id VARCHAR(36) NOT NULL,
created_at DATETIME,
updated_at DATETIME,
deleted_at DATETIME,
deleted VARCHAR(36),
PRIMARY KEY (id),
FOREIGN KEY(endpoint_id) REFERENCES endpoint (id),
FOREIGN KEY(region_id) REFERENCES region (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-01-24 11:18:09.558 3351 ERROR coriolis Traceback (most recent call last):
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
2024-01-24 11:18:09.558 3351 ERROR coriolis self.dialect.do_execute(
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
2024-01-24 11:18:09.558 3351 ERROR coriolis cursor.execute(statement, parameters)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 148, in execute
2024-01-24 11:18:09.558 3351 ERROR coriolis result = self._query(query)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 310, in _query
2024-01-24 11:18:09.558 3351 ERROR coriolis conn.query(q)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 548, in query
2024-01-24 11:18:09.558 3351 ERROR coriolis self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 775, in _read_query_result
2024-01-24 11:18:09.558 3351 ERROR coriolis result.read()
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 1156, in read
2024-01-24 11:18:09.558 3351 ERROR coriolis first_packet = self.connection._read_packet()
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 725, in _read_packet
2024-01-24 11:18:09.558 3351 ERROR coriolis packet.raise_for_error()
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
2024-01-24 11:18:09.558 3351 ERROR coriolis err.raise_mysql_exception(self._data)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
2024-01-24 11:18:09.558 3351 ERROR coriolis raise errorclass(errno, errval)
2024-01-24 11:18:09.558 3351 ERROR coriolis pymysql.err.OperationalError: (3780, "Referencing column 'endpoint_id' and referenced column 'id' in foreign key constraint 'endpoint_region_mapping_ibfk_1' are incompatible.")
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:18:09.558 3351 ERROR coriolis The above exception was the direct cause of the following exception:
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:18:09.558 3351 ERROR coriolis Traceback (most recent call last):
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/oslo_db/sqlalchemy/migration.py", line 87, in db_sync
2024-01-24 11:18:09.558 3351 ERROR coriolis migration = versioning_api.upgrade(engine, repository, version)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/migrate/versioning/api.py", line 186, in upgrade
2024-01-24 11:18:09.558 3351 ERROR coriolis return _migrate(url, repository, version, upgrade=True, err=err, **opts)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "", line 2, in _migrate
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/migrate/versioning/util/init.py", line 167, in with_engine
2024-01-24 11:18:09.558 3351 ERROR coriolis return f(*a, **kw)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/migrate/versioning/api.py", line 366, in _migrate
2024-01-24 11:18:09.558 3351 ERROR coriolis schema.runchange(ver, change, changeset.step)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/migrate/versioning/schema.py", line 93, in runchange
2024-01-24 11:18:09.558 3351 ERROR coriolis change.run(self.engine, step)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/migrate/versioning/script/py.py", line 154, in run
2024-01-24 11:18:09.558 3351 ERROR coriolis script_func(engine)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/local/lib/python3.10/dist-packages/coriolis/db/sqlalchemy/migrate_repo/versions/014_adds_worker_service_regions.py", line 119, in upgrade
2024-01-24 11:18:09.558 3351 ERROR coriolis table.create()
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/sql/schema.py", line 950, in create
2024-01-24 11:18:09.558 3351 ERROR coriolis bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 3117, in _run_ddl_visitor
2024-01-24 11:18:09.558 3351 ERROR coriolis conn._run_ddl_visitor(visitorcallable, element, **kwargs)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2113, in _run_ddl_visitor
2024-01-24 11:18:09.558 3351 ERROR coriolis visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
2024-01-24 11:18:09.558 3351 ERROR coriolis return meth(obj, **kw)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 893, in visit_table
2024-01-24 11:18:09.558 3351 ERROR coriolis self.connection.execute(
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1289, in execute
2024-01-24 11:18:09.558 3351 ERROR coriolis return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
2024-01-24 11:18:09.558 3351 ERROR coriolis return connection._execute_ddl(
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1381, in _execute_ddl
2024-01-24 11:18:09.558 3351 ERROR coriolis ret = self._execute_context(
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1845, in execute_context
2024-01-24 11:18:09.558 3351 ERROR coriolis self.handle_dbapi_exception(
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2024, in handle_dbapi_exception
2024-01-24 11:18:09.558 3351 ERROR coriolis util.raise(newraise, with_traceback=exc_info[2], from=e)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 207, in raise
2024-01-24 11:18:09.558 3351 ERROR coriolis raise exception
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
2024-01-24 11:18:09.558 3351 ERROR coriolis self.dialect.do_execute(
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
2024-01-24 11:18:09.558 3351 ERROR coriolis cursor.execute(statement, parameters)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 148, in execute
2024-01-24 11:18:09.558 3351 ERROR coriolis result = self._query(query)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 310, in _query
2024-01-24 11:18:09.558 3351 ERROR coriolis conn.query(q)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 548, in query
2024-01-24 11:18:09.558 3351 ERROR coriolis self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 775, in _read_query_result
2024-01-24 11:18:09.558 3351 ERROR coriolis result.read()
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 1156, in read
2024-01-24 11:18:09.558 3351 ERROR coriolis first_packet = self.connection._read_packet()
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 725, in _read_packet
2024-01-24 11:18:09.558 3351 ERROR coriolis packet.raise_for_error()
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
2024-01-24 11:18:09.558 3351 ERROR coriolis err.raise_mysql_exception(self._data)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
2024-01-24 11:18:09.558 3351 ERROR coriolis raise errorclass(errno, errval)
2024-01-24 11:18:09.558 3351 ERROR coriolis sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (3780, "Referencing column 'endpoint_id' and referenced column 'id' in foreign key constraint 'endpoint_region_mapping_ibfk_1' are incompatible.")
2024-01-24 11:18:09.558 3351 ERROR coriolis [SQL:
2024-01-24 11:18:09.558 3351 ERROR coriolis CREATE TABLE endpoint_region_mapping (
2024-01-24 11:18:09.558 3351 ERROR coriolis id VARCHAR(36) NOT NULL,
2024-01-24 11:18:09.558 3351 ERROR coriolis endpoint_id VARCHAR(36) NOT NULL,
2024-01-24 11:18:09.558 3351 ERROR coriolis region_id VARCHAR(36) NOT NULL,
2024-01-24 11:18:09.558 3351 ERROR coriolis created_at DATETIME,
2024-01-24 11:18:09.558 3351 ERROR coriolis updated_at DATETIME,
2024-01-24 11:18:09.558 3351 ERROR coriolis deleted_at DATETIME,
2024-01-24 11:18:09.558 3351 ERROR coriolis deleted VARCHAR(36),
2024-01-24 11:18:09.558 3351 ERROR coriolis PRIMARY KEY (id),
2024-01-24 11:18:09.558 3351 ERROR coriolis FOREIGN KEY(endpoint_id) REFERENCES endpoint (id),
2024-01-24 11:18:09.558 3351 ERROR coriolis FOREIGN KEY(region_id) REFERENCES region (id)
2024-01-24 11:18:09.558 3351 ERROR coriolis )
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:18:09.558 3351 ERROR coriolis ]
2024-01-24 11:18:09.558 3351 ERROR coriolis (Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:18:09.558 3351 ERROR coriolis During handling of the above exception, another exception occurred:
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:18:09.558 3351 ERROR coriolis Traceback (most recent call last):
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/root/coriolis-resources/coriolis/coriolis/cmd/db_sync.py", line 23, in
2024-01-24 11:18:09.558 3351 ERROR coriolis main()
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/root/coriolis-resources/coriolis/coriolis/cmd/db_sync.py", line 19, in main
2024-01-24 11:18:09.558 3351 ERROR coriolis db_api.db_sync(db_api.get_engine())
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/local/lib/python3.10/dist-packages/coriolis/db/api.py", line 41, in db_sync
2024-01-24 11:18:09.558 3351 ERROR coriolis return IMPL.db_sync(engine, version=version)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/local/lib/python3.10/dist-packages/coriolis/db/sqlalchemy/api.py", line 46, in db_sync
2024-01-24 11:18:09.558 3351 ERROR coriolis return migration.db_sync(engine, version=version)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/local/lib/python3.10/dist-packages/coriolis/db/sqlalchemy/migration.py", line 14, in db_sync
2024-01-24 11:18:09.558 3351 ERROR coriolis return oslo_migration.db_sync(engine, path, version,
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/debtcollector/removals.py", line 242, in wrapper
2024-01-24 11:18:09.558 3351 ERROR coriolis return f(*args, **kwargs)
2024-01-24 11:18:09.558 3351 ERROR coriolis File "/usr/lib/python3/dist-packages/oslo_db/sqlalchemy/migration.py", line 89, in db_sync
2024-01-24 11:18:09.558 3351 ERROR coriolis raise exception.DBMigrationError(ex)
2024-01-24 11:18:09.558 3351 ERROR coriolis oslo_db.exception.DBMigrationError: (pymysql.err.OperationalError) (3780, "Referencing column 'endpoint_id' and referenced column 'id' in foreign key constraint 'endpoint_region_mapping_ibfk_1' are incompatible.")
2024-01-24 11:18:09.558 3351 ERROR coriolis [SQL:
2024-01-24 11:18:09.558 3351 ERROR coriolis CREATE TABLE endpoint_region_mapping (
2024-01-24 11:18:09.558 3351 ERROR coriolis id VARCHAR(36) NOT NULL,
2024-01-24 11:18:09.558 3351 ERROR coriolis endpoint_id VARCHAR(36) NOT NULL,
2024-01-24 11:18:09.558 3351 ERROR coriolis region_id VARCHAR(36) NOT NULL,
2024-01-24 11:18:09.558 3351 ERROR coriolis created_at DATETIME,
2024-01-24 11:18:09.558 3351 ERROR coriolis updated_at DATETIME,
2024-01-24 11:18:09.558 3351 ERROR coriolis deleted_at DATETIME,
2024-01-24 11:18:09.558 3351 ERROR coriolis deleted VARCHAR(36),
2024-01-24 11:18:09.558 3351 ERROR coriolis PRIMARY KEY (id),
2024-01-24 11:18:09.558 3351 ERROR coriolis FOREIGN KEY(endpoint_id) REFERENCES endpoint (id),
2024-01-24 11:18:09.558 3351 ERROR coriolis FOREIGN KEY(region_id) REFERENCES region (id)
2024-01-24 11:18:09.558 3351 ERROR coriolis )
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:18:09.558 3351 ERROR coriolis ]
2024-01-24 11:18:09.558 3351 ERROR coriolis (Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:36:11.509 2772 INFO migrate.versioning.api [-] 13 -> 14...
2024-01-24 11:36:11.572 2772 CRITICAL coriolis [-] Unhandled error: oslo_db.exception.DBMigrationError: (pymysql.err.OperationalError) (3780, "Referencing column 'endpoint_id' and referenced column 'id' in foreign key constraint 'endpoint_region_mapping_ibfk_1' are incompatible.")
[SQL:
CREATE TABLE endpoint_region_mapping (
id VARCHAR(36) NOT NULL,
endpoint_id VARCHAR(36) NOT NULL,
region_id VARCHAR(36) NOT NULL,
created_at DATETIME,
updated_at DATETIME,
deleted_at DATETIME,
deleted VARCHAR(36),
PRIMARY KEY (id),
FOREIGN KEY(endpoint_id) REFERENCES endpoint (id),
FOREIGN KEY(region_id) REFERENCES region (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-01-24 11:36:11.572 2772 ERROR coriolis Traceback (most recent call last):
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
2024-01-24 11:36:11.572 2772 ERROR coriolis self.dialect.do_execute(
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
2024-01-24 11:36:11.572 2772 ERROR coriolis cursor.execute(statement, parameters)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 148, in execute
2024-01-24 11:36:11.572 2772 ERROR coriolis result = self._query(query)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 310, in _query
2024-01-24 11:36:11.572 2772 ERROR coriolis conn.query(q)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 548, in query
2024-01-24 11:36:11.572 2772 ERROR coriolis self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 775, in _read_query_result
2024-01-24 11:36:11.572 2772 ERROR coriolis result.read()
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 1156, in read
2024-01-24 11:36:11.572 2772 ERROR coriolis first_packet = self.connection._read_packet()
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 725, in _read_packet
2024-01-24 11:36:11.572 2772 ERROR coriolis packet.raise_for_error()
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
2024-01-24 11:36:11.572 2772 ERROR coriolis err.raise_mysql_exception(self._data)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
2024-01-24 11:36:11.572 2772 ERROR coriolis raise errorclass(errno, errval)
2024-01-24 11:36:11.572 2772 ERROR coriolis pymysql.err.OperationalError: (3780, "Referencing column 'endpoint_id' and referenced column 'id' in foreign key constraint 'endpoint_region_mapping_ibfk_1' are incompatible.")
2024-01-24 11:36:11.572 2772 ERROR coriolis
2024-01-24 11:36:11.572 2772 ERROR coriolis The above exception was the direct cause of the following exception:
2024-01-24 11:36:11.572 2772 ERROR coriolis
2024-01-24 11:36:11.572 2772 ERROR coriolis Traceback (most recent call last):
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/oslo_db/sqlalchemy/migration.py", line 87, in db_sync
2024-01-24 11:36:11.572 2772 ERROR coriolis migration = versioning_api.upgrade(engine, repository, version)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/migrate/versioning/api.py", line 186, in upgrade
2024-01-24 11:36:11.572 2772 ERROR coriolis return _migrate(url, repository, version, upgrade=True, err=err, **opts)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "", line 2, in _migrate
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/migrate/versioning/util/init.py", line 167, in with_engine
2024-01-24 11:36:11.572 2772 ERROR coriolis return f(*a, **kw)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/migrate/versioning/api.py", line 366, in _migrate
2024-01-24 11:36:11.572 2772 ERROR coriolis schema.runchange(ver, change, changeset.step)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/migrate/versioning/schema.py", line 93, in runchange
2024-01-24 11:36:11.572 2772 ERROR coriolis change.run(self.engine, step)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/migrate/versioning/script/py.py", line 154, in run
2024-01-24 11:36:11.572 2772 ERROR coriolis script_func(engine)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/local/lib/python3.10/dist-packages/coriolis/db/sqlalchemy/migrate_repo/versions/014_adds_worker_service_regions.py", line 119, in upgrade
2024-01-24 11:36:11.572 2772 ERROR coriolis table.create()
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/sql/schema.py", line 950, in create
2024-01-24 11:36:11.572 2772 ERROR coriolis bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 3117, in _run_ddl_visitor
2024-01-24 11:36:11.572 2772 ERROR coriolis conn._run_ddl_visitor(visitorcallable, element, **kwargs)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2113, in _run_ddl_visitor
2024-01-24 11:36:11.572 2772 ERROR coriolis visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
2024-01-24 11:36:11.572 2772 ERROR coriolis return meth(obj, **kw)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 893, in visit_table
2024-01-24 11:36:11.572 2772 ERROR coriolis self.connection.execute(
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1289, in execute
2024-01-24 11:36:11.572 2772 ERROR coriolis return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
2024-01-24 11:36:11.572 2772 ERROR coriolis return connection._execute_ddl(
2024-01-24 11:36:11.572 2772 ERROR coriolis File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1381, in _execute_ddl
2024-01-24 11:36:11.572 2772 ERROR coriolis ret = self._execute_context(

**Comment by aznashwan** [comment]
Hello @shurdanil, and thank you for your interest in Coriolis!

I have noticed in a separate issue you had opened on the client lib (https://github.com/cloudbase/python-coriolisclient/issues/76) that you mentioned trying to use this setup script:

> Made installation by https://github.com/cloudbase/coriolis-resources/blob/master/install_coriolis.sh

As mentioned in the reply to that issue, Coriolis has evolved a lot over the years (such as the addition of regions for endpoints, which is the issue you're currently having), so that install script should be considered obsoleted in favor of the OpenStack Kolla-based approach we use in the Coriolis VM appliance images we offer.

Please reach out to us via the [contact form on Coriolis' page on our website](https://cloudbase.it/coriolis/) so we can hook you up with a trial appliance through that channel.
